### ISSUE TITLE
[riti] Submodule causes engine to crash

### ISSUE THREAD

**Issue by ahmubashshir** [OpenBangla/OpenBangla-Keyboard#251]
After running `RUST_BACKTRACE=1 ibus-daemon -rxv` it dumped
```
...
[OpenBangla-Info]: [IM:iBus]: Creating IM Engine
[OpenBangla-Info]: [IM:iBus]: IM enabled
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/fixed/parser.rs:30:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
...
```
which is not present in current tree.

### Edit

After Updating submodule, it crashes on `src/fixed/method.rs:100:66`
```
$ RUST_BACKTRACE=full ibus-daemon -rxv
...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/fixed/method.rs:100:66
stack backtrace:
   0:     0x55c79abfd180 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7e7c5f80320a5555
   1:     0x55c79ac6a86c - core::fmt::write::hc2943c27b07a73ca
   2:     0x55c79abed955 - <unknown>
   3:     0x55c79ac00f8b - <unknown>
   4:     0x55c79ac00a61 - <unknown>
   5:     0x55c79ac017a4 - std::panicking::rust_panic_with_hook::h4e2752775b3d350d
   6:     0x55c79ac01247 - <unknown>
   7:     0x55c79abfd67c - <unknown>
   8:     0x55c79ac011d9 - rust_begin_unwind
   9:     0x55c79a8f2fa1 - core::panicking::panic_fmt::h684942b93bd34e24
  10:     0x55c79a8f2eed - core::panicking::panic::h85bfc14fdc3b19ad
  11:     0x55c79a90ec87 - <unknown>
  12:     0x55c79a908fb8 - <unknown>
  13:     0x55c79a8fd6c9 - <unknown>
  14:     0x55c79a8fd041 - <unknown>
  15:     0x55c79a8f8870 - riti_context_new_with_config
  16:     0x55c79a8f3d84 - main
  17:     0x7f16a98f4b25 - __libc_start_main
  18:     0x55c79a8f3e8e - _start
  19:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
...
```

**Comment by mominul** [comment]
@ahmubashshir are you facing this issue or it is resolved?

**Comment by ahmubashshir** [comment]
On Tue, Jul 12 2022 at 09:47:04 AM -0700, Muhammad Mominul Huque 
***@***.***> wrote:
> @ahmubashshir are you facing this issue or it is resolved?
> 
Yeah, it's resolved now.

	Mubashshir

**Comment by mominul** [comment]
Closing as resolved
